from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class OrochiNewAssets: 
	# Image Rule Assets
	# 战斗结算中的突破券。需要全图匹配，当前match只返回最高相似度区域，因此不支持多张突破券场景 
	I_TOPPA_SCROLL = RuleImage(roi_front=(403,179,93,96), roi_back=(0,0,1280,720), threshold=0.8, method="Template matching", file="./tasks/OrochiNew/res/res_toppa_scroll.png")
	# 场景检测：战斗胜利 
	I_OROCHI_SUCCEED = RuleImage(roi_front=(550,485,71,48), roi_back=(550,485,71,48), threshold=0.8, method="Template matching", file="./tasks/OrochiNew/res/win_550_485_71_48.png")
	# 场景检测：战斗胜利2
	I_OROCHI_SUCCEED2 = RuleImage(roi_front=(56,639,41,36), roi_back=(56,639,41,36), threshold=0.8, method="Template matching", file="./tasks/OrochiNew/res/win_56_639_41_36.png")
	# 场景检测：战斗失败 
	I_OROCHI_FAILED = RuleImage(roi_front=(550,485,88,52), roi_back=(550,485,88,52), threshold=0.8, method="Template matching", file="./tasks/OrochiNew/res/fail_550_485_88_52.png")
	# 场景检测：组队
	I_OROCHI_PREPARE = RuleImage(roi_front=(795,33,39,42), roi_back=(795,33,39,42), threshold=0.8, method="Template matching", file="./tasks/OrochiNew/res/orochi_prepare_buf_795_33_39_42.png")
	# 挑战
	I_OROCHI_FIRE = RuleImage(roi_front=(1188,618,58,42), roi_back=(1188,618,58,42), threshold=0.8, method="Template matching", file="./tasks/OrochiNew/res/orochi_fire_1188_618_58_42.png")

	# List Rule Assets
	# 这个是御魂界面选择不同层数的 
	L_LAYER_LIST_NEW = RuleList(folder="./tasks/OrochiNew - 副本/res", direction="vertical", mode="ocr", roi_back=(430,190,160,370), size=(45, 88), 
					 array=["壹", "贰", "叁", "肆", "伍", "陆", "柒", "捌", "玖", "拾", "悲", "神"])


	# Ocr Rule Assets
	# 突破卷的数量 
	O_TOPPA_SCROLL = RuleOcr(roi=(1143,13,80,39), area=(0,0,100,100), mode="DigitCounter", method="Default", keyword="", name="toppa_scroll")


