from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class BreedAssets: 

	# Image Rule Assets
	I_CONTINUE_BREEDING = RuleImage(roi_front=(627,595,145,46), roi_back=(627,595,145,46), threshold=0.8, method="Template matching", file="./tasks/ContinueBreed/res/continue_to_breed_627,595,145,46.png")
	I_BREEDING_CONFIRM = RuleImage(roi_front=(817,627,113,45), roi_back=(817,627,113,45), threshold=0.8, method="Template matching", file="./tasks/ContinueBreed/res/continue_to_breed_817,627,113,45.png")

	# Ocr Rule Assets
	# Ocr-description 
	O_BREED_OCR = RuleOcr(roi=(126,136,360,491), area=(126,136,360,491), mode="Full", method="Default", keyword="", name="o_breed_ocr")


